# More examples: https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml

name: Cypress Tests
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      NEXT_PUBLIC_ALGOLIA_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_KEY }}
      NEXT_PUBLIC_ALGOLIA_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_ID }}
      AUTHORIZE_LOGIN_ID: ${{ secrets.AUTHORIZE_LOGIN_ID }}
      AUTHORIZE_TRANSACTION_KEY: ${{ secrets.AUTHORIZE_TRANSACTION_KEY }}
      AUTHORIZE_IFRAME_COMMUNICATOR_URL: ${{ secrets.AUTHORIZE_IFRAME_COMMUNICATOR_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup code
        run: yarn

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/**/*
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
